// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTCzRdBQGVQiIeBJ3S10PkSSvTCtOgL_8',
    appId: '1:488120930979:web:154394b14d41433f8a6516',
    messagingSenderId: '488120930979',
    projectId: 'ecom-app-33fca',
    authDomain: 'ecom-app-33fca.firebaseapp.com',
    storageBucket: 'ecom-app-33fca.firebasestorage.app',
    measurementId: 'G-8GG9VFMQK4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOWRy5If-WpoDCNe5EcN4cMnB9ngNXuSA',
    appId: '1:488120930979:android:913de9141133919f8a6516',
    messagingSenderId: '488120930979',
    projectId: 'ecom-app-33fca',
    storageBucket: 'ecom-app-33fca.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTCzRdBQGVQiIeBJ3S10PkSSvTCtOgL_8',
    appId: '1:488120930979:web:34f72ae1c349f9a18a6516',
    messagingSenderId: '488120930979',
    projectId: 'ecom-app-33fca',
    authDomain: 'ecom-app-33fca.firebaseapp.com',
    storageBucket: 'ecom-app-33fca.firebasestorage.app',
    measurementId: 'G-447JPNFW42',
  );
}
